server.port: 8081
eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      routes:
      - id: user
        uri: lb://user
        predicates:
        - Path=/user/**
      - id: train
        uri: lb://train
        predicates:
        - Path=/train/**
      - id: booking
        uri: lb://booking
        predicates:
        - Path=/booking/**
      discovery:
        locator:
          enabled: true